<a href="https://colab.research.google.com/github/J-o-y-y/Fintech_data_analysis/blob/main/%EC%88%9C%ED%99%98%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EC%97%B0%EC%8A%B5_RNN(Recurrent_Neural_Network).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
train_X = [[1,2,3,4,5],
           [2,4,6,8,10],
           [1,3,5,7,9],
           [0,2,4,6,8]]
print(np.shape(train_X))

(4, 5)


In [3]:
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(4, 5)


In [4]:
train_X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.],
       [ 1.,  3.,  5.,  7.,  9.],
       [ 0.,  2.,  4.,  6.,  8.]], dtype=float32)

In [6]:
train_X = np.array([train_X], dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [8]:
hidden_size = 3
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=False)
hidden_state = rnn(train_X)

print('hidden_state : {} .t shape : {}'.format (hidden_state, hidden_state.shape))

hidden_state : [[[ 0.99932665  0.9278535  -0.9847413 ]
  [ 1.          0.99884814 -0.99697536]
  [ 0.9999975   0.9980813  -0.9642103 ]
  [ 0.9999741   0.99671316 -0.67630905]]] .t shape : (1, 4, 3)


In [9]:
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=False)
hidden_state = rnn(train_X)

In [12]:
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden_state : {} / t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state : {} /t shape : {}'.format(last_state, last_state.shape))

hidden_state : [[[-0.9968895   0.9583004  -0.11406533]
  [-0.99999964  0.99881953  0.22919552]
  [-0.99999917  0.9954938  -0.6581593 ]
  [-0.999996    0.99146277 -0.58491606]]] / t shape : (1, 4, 3)
last_state : [[-0.999996    0.99146277 -0.58491606]] /t shape : (1, 3)


In [17]:
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden_state : {} /t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state : {} /t shape : {}'.format(last_state, last_state.shape))

hidden_state : [[ 0.9398323 -0.9999795  0.9978273]] /t shape : (1, 3)
last_state : [[ 0.9398323 -0.9999795  0.9978273]] /t shape : (1, 3)
